language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: MjDeDqyU4k0vqAIb0ED34aiDTQYW3W7fRJZgFppwOd4z7pm+guDicPkU/Wu8Y6XikYTdcHXRkac/8SDed95qLCXa5msxRipYovHUWWXAqfxF51XdJAb92U7jjVFAQuFetiVNf8Cro9i9CmfRG3UwLUxEXM8m+OGVMEf+4TmJSxj/s13I8FczMbCWTKgqof/bNwDilPTOShVHs62FA75OdzCQQroThhsrfBF2IF8TyqS/S9/vQ71I/29xy7mLIGjbS6xZ/upuqNSaJkkC6k2fo5BxarYWeM7yArqKI4yxgwnt9BXEM9uyhp13MxHcBGdsLQqtscptml8GEqb49ykc9kQPZGNzywYlfy/NsVonbR8LBTUBy3m0Y0eyu5rpSq+nRumqxtcRuMQinFRZlGmoIyNZK55WQlL/UUFIGTSwhhg6YVP/LpuwWnjdtkWr89kXaGFmpljV9qlpbPRLlUoWvNF50/OjEckpidca+3HjfA4fFOYEvB4+Wf14/u325dpualgl3fMZ0rcHMAeTh+rk7AAca3qsTm2PH5iD6jn9KsCRCJb/XBcK2gdf3VcUKjGWZn7/vDLDzBCkujsWukB5g7+QSUUpVBRlJuTyGZlfZi5CE3i49suaKsmc+ynZSPqPooGbGZmvqhCk7g6Vx36WD/K7vLAsGIB4w9GLJt/g2Zc=
  app: whattoreadbot
  on:
    repo: mavilam/what_to_read_bot
