language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: HwEBCYflANZezo8EFixc2hzcC9fNEN5tT8hfIhjuPDgVJtxZk6S13D5Odlx86t3cbpvz3dUly3q69eoPif3X3P//ebDufpnP4MUqv1O7xIBY4I4nMcIPAtfrdbtzgEqwjZvmfy9GwxfqkSdoyCzolnXpC2qGbkZxnQdZ1yjQM+U6GO7I2hrA0EKByTMHFHsEWdVbar2Vdv19Og5C3qOoOo+G8H0mWTYly5HWt5zlk0GMXZUQCrVLCD6RFoc6z8IEcEZjbn//pvb2mHOn5GflvreFDXjLGOkpCilUPSLNrbUdmPsoZoGWvqy6eo7fl7vu1RXRS5tdoMIInp/QUQ59bBsMJU3VNTF/CMBZK/caR4TTf6WgU4gSXgoFul1tJCX1IRRa5ltvplnTPuYZmKGLBELEYl7CQ0Wh45sk5B6WDLPGsy8rBEHnuOnPX4QMq151HZGvnMulkxlnwy4B/j+9HdZ6tLQM4trY+rPR8ClAXndgeaO9v/CuA4DOkjDDj/X730Nr6OkdmXttIy3GKHIMcW0W7jX5DualTgqPiyV33zYCUMFnZ/2LvXMbS9KATEvb1R88+6xsc5DKNQTyq+SJDSjPU0+/X4tfaMXxKFsCkYwYEYLSKpqu8R/Zp0rfDHHEE7CP75D5ZxjxThyKI5QytVA6OkDJdu3eYB1WFqdwqig=
  app: whattoreadbot
  on:
    repo: mavilam/what_to_read_bot
