language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: vo6HH4C0BZbubo2DsNkzyM0dU0slFRb09CXJVN6yWVOuV0MVNriTycqD6kGJmMS7N528xEf7ei0sMTzED5MraiC461mI2vmFGjaHJfbR57R5+mk7n1fhilrNwdOIPkoTdonYjzIAAWFBY/xCxgiadOQ80TuVUmC5kG46HtOiAa/qk4MB+noCeVeVMTmadgY1B/vC8NWWOzvcrFFsITaUPaj4UNwrpGzCppXz5ELHGP7QMybTI3djA0OCTd2wD6aH+KltOM/uuCXEJAQiWMP6s7D6+SPlTkgTP8z/qE5xdqFQo+V/jZzQfuwLv7XEynLGGUEW1WUQZbcYu52V0mvD3z56iJ7u3C70NVSIGvofgnMY0LmgrL45mRebDT9UrN8vzA07T4GouePl7MjrElViKus5vzzmf8afX7jjZ0V/H0vY3nGAYtIn0BmPgCrvSG216LgRS5YgXOx1JbgAYg1wUl0nK2KWq8k6KiXgtWFj/DFhF3CUFbJgDdDYrAw4bgZZoBzSwP+Zjak8BJhDiuKkong3kbUzjLDh8fFaoH7N2JpFE2pRfLK6CtEhVH+FhQGYY0m+8od3Nnw4Xwszt/wJe0BPqHB47g8VAljk4iFUs+pKLhPkApowxtq1nqxk63GNgkfkjMWNJEV6mbNkt1Npbq88E1YOpciSvckqTdEecic=
  app: whattoreadbot
  on:
    repo: mavilam/what_to_read_bot
